- id: movielights
  alias: Movie Lights
  trigger:
  - platform: state
    from: playing
    to: paused
    entity_id: media_player.plex_umbriel
    id: paused
  - platform: state
    to: playing
    entity_id: media_player.plex_umbriel
    id: playing
  - platform: state
    from: playing
    to: idle
    entity_id: media_player.plex_umbriel
    id: ended
  - platform: state
    to: idle
    entity_id: media_player.plex_umbriel
    id: stopped
  condition:
  - condition: or
    conditions:
    - condition: state
      entity_id: media_player.plex_umbriel
      state: movie
      attribute: media_content_type
    - condition: state
      entity_id: media_player.plex_umbriel
      state: tvshow
      attribute: media_content_type
  action:
  - choose:
    - conditions:
      - condition: trigger
        id: paused
      sequence:
      - service: light.turn_on
        data:
          brightness_pct: 1
        target:
          entity_id: light.livingroom_pots
    - conditions:
      - condition: or
        conditions:
        - condition: trigger
          id: ended
        - condition: trigger
          id: stopped
      sequence:
      - service: light.turn_on
        data:
          transition: 10
          brightness_pct: 30
        target:
          entity_id: light.livingroom_pots
    - conditions:
      - condition: trigger
        id: playing
      sequence:
      - service: light.turn_off
        target:
          entity_id: light.livingroom_pots
        data: {}
    default: []
- id: alistairmainirbrightness
  alias: Alistair Main IR Brightness
  trigger:
  - platform: state
    entity_id: input_number.alistair_main_ir
  action:
  - service: lifx.set_state
    entity_id: light.alistair_main
    data_template:
      infrared: '{{ states(''input_number.alistair_main_ir'') | int }}'
  initial_state: true
  mode: single
- id: alistairnightlighttransition
  alias: Alistair Nightlight
  trigger:
  action:
  - service: lifx.set_state
    data:
      entity_id: light.alistair_main
      brightness_pct: 1
      transition: 10
      hs_color:
      - 37
      - 100
      power: true
  mode: single
- id: '1598760479433'
  alias: Light off White Noise on
  description: ''
  trigger:
  - device_id: 7baa77eeb6604448a7c10fb87d16a286
    domain: light
    entity_id: light.alistair_main
    platform: device
    type: turned_off
  condition:
  - condition: state
    state: 'on'
    entity_id: input_boolean.alistair_sound_trigger
  action:
  - data:
      entity_id: media_player.alistair_room
    service: sonos.unjoin
  - data:
      entity_id: media_player.alistair_room
      volume_level: 0.13
    service: media_player.volume_set
  - data:
      entity_id: media_player.alistair_room
      source: Baby
    service: media_player.select_source
  - service: media_player.repeat_set
    data:
      repeat: one
    target:
      entity_id: media_player.alistair_room
  - device_id: 7baa77eeb6604448a7c10fb87d16a286
    domain: light
    entity_id: light.alistair_main
    type: turn_off
  - service: input_number.set_value
    data:
      value: 255
    target:
      entity_id: input_number.alistair_main_ir
  mode: single
- id: '1598804150280'
  alias: Light on White Noise off
  description: ''
  trigger:
  - entity_id: light.alistair_main
    platform: state
  condition:
  - condition: template
    value_template: '{{ states.light.alistair_main.attributes.brightness > 10 }}'
  - condition: state
    entity_id: media_player.alistair_room
    attribute: media_content_id
    state: x-file-cifs://10.0.0.10/media/Music/Sounds/Baby/Pink%20Noise%20HQ%20Audio.m4a
  - condition: state
    entity_id: media_player.alistair_room
    state: playing
  action:
  - data:
      entity_id: media_player.alistair_room
      sleep_time: 0
    service: sonos.set_sleep_timer
  - service: input_number.set_value
    target:
      entity_id: input_number.alistair_main_ir
    data:
      value: 0
  mode: single
- id: '1598808585001'
  alias: Alistair Reading Light
  description: ''
  trigger: []
  condition: []
  action:
  - data:
      brightness_pct: 30
      entity_id: light.alistair_main
      hs_color:
      - 40
      - 50
      power: 'on'
      transition: 5
    service: lifx.set_state
  - delay:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
  - service: input_boolean.turn_on
    entity_id: input_boolean.alistair_sound_trigger
  - delay: 00:20:00
  - service: input_boolean.turn_off
    entity_id: input_boolean.alistair_sound_trigger
  mode: restart
- id: '1599327200195'
  alias: Sound Trigger off when brightness above 30%
  description: ''
  trigger:
  - entity_id: light.alistair_main
    platform: state
  condition:
  - condition: template
    value_template: '{{ states.light.alistair_main.attributes.brightness > 85 }}'
  action:
  - data: {}
    entity_id: input_boolean.alistair_sound_trigger
    service: input_boolean.turn_off
  mode: single
- id: '1607901677018'
  alias: Alistair Reading Light Long
  description: ''
  trigger: []
  condition: []
  action:
  - data:
      brightness_pct: 30
      entity_id: light.alistair_main
      hs_color:
      - 40
      - 50
      power: 'on'
      transition: '{{ states(''input_number.fade_time'') | int * 60 }}'
    service: lifx.set_state
  - delay:
      hours: 0
      minutes: '{{ states(''input_number.fade_time'') | int }}'
      seconds: 0
      milliseconds: 0
  - service: input_boolean.turn_on
    entity_id: input_boolean.alistair_sound_trigger
  - delay:
      hours: 0
      minutes: 25
      seconds: 0
      milliseconds: 0
  - service: input_boolean.turn_off
    entity_id: input_boolean.alistair_sound_trigger
  mode: restart
- id: '1613327902048'
  alias: SaA Webhhok Kyle
  description: ''
  trigger:
  - platform: webhook
    webhook_id: sleepasandroidkyle
  condition: []
  action:
  - service: input_text.set_value
    data:
      value: '{{ trigger.json.event }}'
    entity_id: input_text.saa_kyle
  mode: single
- id: '1613330813566'
  alias: SaA Webhook Allynn
  description: ''
  trigger:
  - platform: webhook
    webhook_id: sleepasandroidallynn
  condition: []
  action:
  - service: input_text.set_value
    data:
      value: '{{ trigger.json.event }}'
    entity_id: input_text.saa_allynn
  mode: single
- id: '1614033386075'
  alias: Notify Kyle if music is playing while asleep
  description: ''
  trigger:
  - platform: state
    entity_id: media_player.living_room
    to: playing
  condition:
  - condition: not
    conditions:
    - condition: or
      conditions:
      - condition: state
        entity_id: input_text.saa_kyle
        state: sleep_tracking_stopped
      - condition: state
        entity_id: input_text.saa_kyle
        state: alarm_alert_dismiss
  action:
  - service: notify.mobile_app_oneplus5t
    data:
      message: A song was played while you were sleeping. Check Last.fm
      title: Music Scrobbled
      data:
        clickAction: https://last.fm/user/Undearius
  mode: single
- id: '1614033769366'
  alias: Notify Kyle if Allynn left her computer on
  description: ''
  trigger:
  - platform: state
    entity_id: input_text.saa_allynn
    to: sleep_tracking_started
  - platform: state
    entity_id: person.allynn
    from: home
  condition:
  - condition: state
    entity_id: device_tracker.allynnscomputer
    state: home
  action:
  - service: notify.mobile_app_oneplus5t
    data:
      title: Computer Running
      message: Allynn left her computer on. Shut it off.
  mode: single
- id: '1615074707979'
  alias: Notify if Thermostat becomes unavailable
  description: ''
  trigger:
  - platform: state
    entity_id: climate.thermostat
    to: unavailable
    for:
      hours: 0
      minutes: 1
      seconds: 0
  - platform: state
    entity_id: climate.thermostat
    attribute: current_temperature
    to: '0'
    for:
      hours: 0
      minutes: 0
      seconds: 30
  condition: []
  action:
  - service: notify.mobile_app_sm_a515w
    data:
      title: Thermostat Unavailable
      message: Check to see if the furnace is on!
      data:
        clickAction: /lovelace/climate
  - service: notify.mobile_app_oneplus5t
    data:
      title: Thermostat Unavailable
      message: Check to see if the furnace is on!
      data:
        clickAction: /lovelace/climate
  - service: notify.mobile_app_oneplus5t
    data:
      message: TTS
      title: Thermostat is offline
      data:
        channel: alarm_stream
  mode: single
- id: '1615075704978'
  alias: Morning Sunrise
  description: ''
  trigger:
  - platform: time
    at: 06:45:00
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - service: script.turn_on
    target:
      entity_id: script.sunrise
    data:
      variables:
        light: light.wled_bed
  mode: single
- id: '1616884736419'
  alias: Close the garage when no one is home
  description: ''
  trigger:
  - platform: state
    entity_id: person.allynn
    to: not_home
  - platform: state
    entity_id: person.kyle
    to: not_home
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: person.allynn
      state: not_home
    - condition: state
      entity_id: person.kyle
      state: not_home
    - condition: state
      entity_id: person.guest
      state: not_home
    - condition: state
      entity_id: cover.garage_door
      state: open
  action:
  - service: cover.close_cover
    target:
      entity_id: cover.garage_door
  mode: single
- id: '1634020365562'
  alias: Let there be light
  description: Turn on all the lights in the kitchen/living room
  trigger:
  - platform: state
    entity_id: binary_sensor.in_wall_smart_motion_dimmer_home_security_motion_detection
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: light.turn_on
    target:
      entity_id:
      - light.livingroom_pots
      - light.dining_table
      - light.kitchen
      - light.living_room_main
      - light.sink_lights
    data:
      brightness_pct: 100
  mode: single
- id: '1637868774108'
  alias: Clock Chimes - Minutes
  description: ''
  trigger:
  - platform: time_pattern
    minutes: /15
  condition:
  - condition: template
    value_template: '{{ now().minute > 10 and now().minute < 50 }}'
  - condition: not
    conditions:
    - condition: state
      entity_id: media_player.living_room
      state: playing
  action:
  - data:
      entity_id: media_player.living_room
    service: sonos.unjoin
  - data:
      volume_level: 0.25
    service: media_player.volume_set
    target:
      entity_id: media_player.living_room
  - service: media_player.play_media
    data:
      media_content_id: x-file-cifs://10.0.0.10/docs/kyle/Documents/Projects/Clock
        Chimes/{{ now().minute }}.mp3
      media_content_type: music
    target:
      entity_id: media_player.living_room
  mode: single
- id: '1637870310658'
  alias: Clock Chimes - Hour
  description: ''
  trigger:
  - platform: time_pattern
    hours: '*'
    seconds: '39'
    minutes: '59'
  condition:
  - condition: time
    after: 06:50:00
    before: '21:05:00'
  - condition: not
    conditions:
    - condition: state
      entity_id: media_player.living_room
      state: playing
  action:
  - data:
      entity_id: media_player.living_room
    service: sonos.unjoin
  - data:
      volume_level: 0.25
    service: media_player.volume_set
    target:
      entity_id: media_player.living_room
  - service: media_player.clear_playlist
    target:
      entity_id: media_player.living_room
  - service: media_player.play_media
    data:
      media_content_id: x-file-cifs://10.0.0.10/docs/kyle/Documents/Projects/Clock
        Chimes/60.mp3
      media_content_type: music
      enqueue: true
    target:
      entity_id: media_player.living_room
  - service: media_player.play_media
    data:
      media_content_id: x-file-cifs://10.0.0.10/docs/kyle/Documents/Projects/Clock
        Chimes/{% if now().hour > 12 %}{{ now().hour - 11 }}{%- else -%}{{ now().hour
        + 1 }}{%- endif %}.mp3
      media_content_type: music
      enqueue: true
    target:
      entity_id: media_player.living_room
  - service: sonos.play_queue
    target:
      entity_id: media_player.living_room
  mode: single
- id: '1639164820573'
  alias: Lights off when no one is home
  description: ''
  trigger:
  - platform: state
    entity_id: person.allynn
    to: not_home
  - platform: state
    entity_id: person.kyle
    to: not_home
  condition:
  - condition: state
    entity_id: person.allynn
    state: not_home
  - condition: state
    entity_id: person.kyle
    state: not_home
  - condition: not
    conditions:
    - condition: state
      entity_id: person.guest
      state: home
  action:
  - service: light.turn_off
    entity_id: all
  - device_id: 7eb71993650f9a57276a8f9e8fd99f6d
    domain: cover
    entity_id: cover.garage_door
    type: close
  mode: single
- id: '1641689543179'
  alias: Pot lights on motion
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.living_room_dimmer_motion
    from: 'off'
    to: 'on'
  - platform: state
    entity_id: input_boolean.potsoverride
  condition:
  - condition: state
    entity_id: input_boolean.potsoverride
    state: 'off'
  - condition: template
    value_template: "{% if states('weather.ottawa_kanata_orleans') in [\"snowy\",\"\
      cloudy\"] %}\n  {% set ele = 7 %}\n{% else %}\n  {% set ele = 6 %}\n{% endif\
      \ %}\n{{ state_attr('sun.sun', 'elevation') < ele }}"
  action:
  - service: light.turn_on
    target:
      entity_id: light.livingroom_pots
    data:
      brightness_pct: "{% if is_state(\"light.livingroom_pots\", \"on\") -%}\n  {{\
        \ (state_attr(\"light.livingroom_pots\", \"brightness\") / 2.55 ) | round\
        \ }}\n{%- else -%}\n  {% if now().hour >=22 or now().hour < 7 %} 1\n  {% elif\
        \ now().hour >= 20 and now().hour < 22 %} 20\n  {% else %} 100\n  {% endif\
        \ %}\n{%- endif %}"
  - wait_template: '{{ is_state("binary_sensor.living_room_dimmer_motion", "off")
      }}'
  - delay:
      minutes: '{% if now().hour >=17 and now().hour < 22 %} 30 {% else %} 15 {% endif
        %}'
  - condition: state
    entity_id: input_boolean.potsoverride
    state: 'off'
  - service: light.turn_off
    target:
      entity_id: light.livingroom_pots
    data: {}
  mode: restart
- id: '1641781795297'
  alias: Notify Kyle if furnace about to turn on
  description: ''
  trigger:
  - platform: state
    entity_id: climate.thermostat
    attribute: current_temperature
    to: '20.7'
  condition: []
  action:
  - service: notify.mobile_app_oneplus5t
    data:
      message: Furnace is about to turn on
  mode: single
- id: '1641799136107'
  alias: Sink lights on motion
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.living_room_dimmer_motion
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: light.turn_on
    target:
      entity_id: light.sink_lights
  - wait_template: '{{ is_state("binary_sensor.living_room_dimmer_motion", "off")
      }}'
  - service: light.turn_off
    target:
      entity_id: light.sink_lights
  mode: restart
- id: '1643432818705'
  alias: Kitchen light on
  description: ''
  trigger:
  - platform: state
    entity_id: light.livingroom_pots
    to: 'on'
  condition:
  - condition: or
    conditions:
    - condition: time
      weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
      after: '16:00:00'
      before: '19:00:00'
    - condition: time
      after: '17:00:00'
      before: '19:00:00'
      weekday:
      - sat
      - sun
    - condition: time
      after: 06:30:00
      before: 08:30:00
      weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  action:
  - service: light.turn_on
    target:
      entity_id: light.kitchen
    data: {}
  mode: single
- id: '1643434691823'
  alias: Welcome home
  description: ''
  trigger:
  - platform: state
    entity_id: person.allynn
    to: home
  condition:
  - condition: time
    after: '16:00:00'
    before: '20:00:00'
  action:
  - service: notify.mobile_app_sm_a515w
    data:
      message: TTS
      title: Welcome home, Allynn
  mode: single
- id: '1644961012560'
  alias: Power off workstation if idle
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.kyle_office_outlet_power
    below: '30'
    for:
      hours: 0
      minutes: 5
      seconds: 0
    above: '0'
  condition: []
  action:
  - service: notify.mobile_app_oneplus5t
    data:
      message: Workstation power left on. Switching off in 5 minutes
      title: Workstation idling
  - delay:
      hours: 0
      minutes: 5
      seconds: 0
      milliseconds: 0
  - service: switch.turn_off
    data: {}
    target:
      entity_id: switch.kyle_office_outlet_relay
  mode: single
- id: '1644967380579'
  alias: Power on workstation
  description: ''
  trigger:
  - platform: time
    at: 08:20:00
  condition:
  - condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'on'
  action:
  - service: switch.turn_on
    data: {}
    target:
      entity_id: switch.kyle_office_outlet_relay
  mode: single
- id: '1645727158023'
  alias: 'Lights: Set porch scene'
  description: ''
  trigger:
  - platform: device
    type: turned_on
    device_id: 06efffd362e64ab2ab3d31b1b9a7536c
    entity_id: light.porch_door
    domain: light
  - platform: device
    type: turned_on
    device_id: 86eeede02253437d93516e7083c15338
    entity_id: light.porch_garage
    domain: light
  condition: []
  action:
  - choose:
    - conditions:
      - condition: template
        value_template: '{{ now().month == 10 }}'
      sequence:
      - service: scene.turn_on
        data: {}
        target:
          entity_id: scene.porch_lights_halloween
    - conditions:
      - condition: template
        value_template: '{{ now().month == 12 and now().day < 30 }}'
      sequence:
      - service: scene.turn_on
        data: {}
        target:
          entity_id:
          - scene.porch_lights_christmas
    default: []
  - service: scene.turn_on
    data: {}
    target:
      entity_id: scene.porch_lights_ukraine
  mode: single
- id: '1645878364914'
  alias: Notify if motion in Alistair's room
  description: ''
  trigger:
  - platform: state
    for:
      hours: 0
      minutes: 1
      seconds: 0
    entity_id: binary_sensor.alistair_room_home_security_motion_detection
    from: 'off'
    to: 'on'
  condition:
  - condition: state
    state: 'on'
    entity_id: light.alistair_main_ir
  action:
  - service: notify.mobile_app_sm_a515w
    data:
      data:
        clickAction: /lovelace/alistair
      message: Something moved in Alistair's room
      title: He's awake!
  - service: notify.mobile_app_sm_a515w
    data:
      message: TTS
      data:
        channel: alarm_stream
      title: Alistair is out of bed
  - service: notify.mobile_app_oneplus5t
    data:
      data:
        clickAction: /lovelace/alistair
      message: Something moved in Alistair's room
      title: He's awake!
  - service: notify.mobile_app_oneplus5t
    data:
      message: TTS
      data:
        channel: alarm_stream
      title: Alistair is out of bed
  mode: single
