- id: moviepaused
  alias: Movie Paused
  trigger:
  - platform: state
    from: playing
    to: paused
    entity_id: media_player.plex_oneplus_5t
  condition:
  - condition: template
    value_template: '{{ is_state_attr(''media_player.plex_oneplus_5t'', ''media_content_type'',
      ''movie'') }}'
  action:
  - service: light.turn_on
    data:
      brightness_pct: 1
    target:
      entity_id: light.livingroom_pots
- id: movieresumed
  alias: Movie Resumed
  trigger:
  - platform: state
    to: playing
    entity_id: media_player.plex_oneplus_5t
  condition:
  - condition: template
    value_template: '{{ is_state_attr(''media_player.plex_oneplus_5t'', ''media_content_type'',
      ''movie'') }}'
  action:
  - service: light.turn_off
    data: {}
    target:
      entity_id: light.livingroom_pots
- id: movieended
  alias: Movie Ended
  trigger:
  - platform: state
    from: playing
    to: idle
    entity_id: media_player.plex_oneplus_5t
  condition:
  - condition: template
    value_template: '{{ is_state_attr(''media_player.plex_oneplus_5t'', ''media_content_type'',
      ''movie'') }}'
  action:
  - service: light.turn_on
    data:
      transition: 10
      brightness_pct: 30
    target:
      entity_id: light.livingroom_pots
  - service: light.turn_on
    data:
      transition: 10
      brightness_pct: 50
      kelvin: 2600
      entity_id:
      - light.bed_main
- id: moviestopped
  alias: Movie Stopped
  trigger:
  - platform: state
    to: idle
    entity_id: media_player.plex_oneplus_5t
  condition:
  - condition: template
    value_template: '{{ is_state_attr(''media_player.plex_oneplus_5t'', ''media_content_type'',
      ''movie'') }}'
  action:
  - service: light.turn_on
    data:
      transition: 10
      brightness_pct: 30
    target:
      entity_id: light.livingroom_pots
- id: babymainirbrightness
  alias: Baby Main IR Brightness
  trigger:
  - platform: state
    entity_id: input_number.baby_main_ir
  action:
  - service: lifx.set_state
    entity_id: light.baby_main
    data_template:
      infrared: '{{ states(''input_number.baby_main_ir'') | int }}'
  initial_state: true
  mode: single
- id: babynightlighttransition
  alias: Baby Nightlight
  trigger:
  action:
  - service: lifx.set_state
    data:
      entity_id: light.baby_main
      brightness_pct: 1
      transition: 10
      hs_color:
      - 37
      - 100
      power: true
  mode: single
- id: '1598760479433'
  alias: Light off White Noise on
  description: ''
  trigger:
  - device_id: 7baa77eeb6604448a7c10fb87d16a286
    domain: light
    entity_id: light.baby_main
    platform: device
    type: turned_off
  condition:
  - condition: state
    state: 'on'
    entity_id: input_boolean.sound_trigger
  action:
  - data:
      entity_id: media_player.baby_room
    service: sonos.unjoin
  - data:
      entity_id: media_player.baby_room
      volume_level: 0.13
    service: media_player.volume_set
  - data:
      entity_id: media_player.baby_room
      source: Baby
    service: media_player.select_source
  - service: media_player.repeat_set
    data:
      repeat: one
    target:
      entity_id: media_player.baby_room
  - device_id: 7baa77eeb6604448a7c10fb87d16a286
    domain: light
    entity_id: light.baby_main
    type: turn_off
  - service: input_number.set_value
    data:
      value: 255
    target:
      entity_id: input_number.baby_main_ir
  mode: single
- id: '1598804150280'
  alias: Light on White Noise off
  description: ''
  trigger:
  - entity_id: light.baby_main
    platform: state
  condition:
  - condition: template
    value_template: '{{ states.light.baby_main.attributes.brightness > 10 }}'
  - condition: state
    entity_id: media_player.baby_room
    attribute: media_content_id
    state: x-file-cifs://10.0.0.10/media/Music/Sounds/Baby/Pink%20Noise%20HQ%20Audio.m4a
  - condition: state
    entity_id: media_player.baby_room
    state: playing
  action:
  - data:
      entity_id: media_player.baby_room
      sleep_time: 0
    service: sonos.set_sleep_timer
  - service: input_number.set_value
    target:
      entity_id: input_number.baby_main_ir
    data:
      value: 0
  mode: single
- id: '1598808585001'
  alias: Baby Reading Light
  description: ''
  trigger: []
  condition: []
  action:
  - data:
      brightness_pct: 30
      entity_id: light.baby_main
      hs_color:
      - 40
      - 50
      power: 'on'
      transition: 5
    service: lifx.set_state
  - delay:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
  - service: input_boolean.turn_on
    entity_id: input_boolean.sound_trigger
  - delay: 00:20:00
  - service: input_boolean.turn_off
    entity_id: input_boolean.sound_trigger
  mode: restart
- id: '1599327200195'
  alias: Sound Trigger off when brightness above 30%
  description: ''
  trigger:
  - entity_id: light.baby_main
    platform: state
  condition:
  - condition: template
    value_template: '{{ states.light.baby_main.attributes.brightness > 85 }}'
  action:
  - data: {}
    entity_id: input_boolean.sound_trigger
    service: input_boolean.turn_off
  mode: single
- id: '1607901677018'
  alias: Baby Reading Light Long
  description: ''
  trigger: []
  condition: []
  action:
  - data:
      brightness_pct: 30
      entity_id: light.baby_main
      hs_color:
      - 40
      - 50
      power: 'on'
      transition: 300
    service: lifx.set_state
  - delay:
      hours: 0
      minutes: 5
      seconds: 0
      milliseconds: 0
  - service: input_boolean.turn_on
    entity_id: input_boolean.sound_trigger
  - delay:
      hours: 0
      minutes: 25
      seconds: 0
      milliseconds: 0
  - service: input_boolean.turn_off
    entity_id: input_boolean.sound_trigger
  mode: restart
- id: '1613327902048'
  alias: SaA Webhhok Kyle
  description: ''
  trigger:
  - platform: webhook
    webhook_id: sleepasandroidkyle
  condition: []
  action:
  - service: input_text.set_value
    data:
      value: '{{ trigger.json.event }}'
    entity_id: input_text.saa_kyle
  mode: single
- id: '1613330813566'
  alias: SaA Webhook Allynn
  description: ''
  trigger:
  - platform: webhook
    webhook_id: sleepasandroidallynn
  condition: []
  action:
  - service: input_text.set_value
    data:
      value: '{{ trigger.json.event }}'
    entity_id: input_text.saa_allynn
  mode: single
- id: '1614033386075'
  alias: Notify Kyle if music is playing while asleep
  description: ''
  trigger:
  - platform: state
    entity_id: media_player.living_room
    to: playing
  condition:
  - condition: not
    conditions:
    - condition: or
      conditions:
      - condition: state
        entity_id: input_text.saa_kyle
        state: sleep_tracking_stopped
      - condition: state
        entity_id: input_text.saa_kyle
        state: alarm_alert_dismiss
  action:
  - service: notify.mobile_app_oneplus_a5010
    data:
      title: Music Scrobbled
      message: Music was playing while you were asleep. Check Last.fm
  mode: single
- id: '1614033769366'
  alias: Notify Kyle if Allynn left her computer on
  description: ''
  trigger:
  - platform: state
    entity_id: input_text.saa_allynn
    to: sleep_tracking_started
  - platform: state
    entity_id: person.allynn
    from: home
  condition:
  - condition: state
    entity_id: device_tracker.allynnscomputer
    state: home
  action:
  - service: notify.mobile_app_oneplus_a5010
    data:
      title: Computer Running
      message: Allynn left her computer on. Shut it off.
  mode: single
- id: '1615074707979'
  alias: Notify Allynn and Kyle if Thermostat becomes unavailable
  description: ''
  trigger:
  - platform: state
    entity_id: climate.thermostat
    to: unavailable
    for:
      hours: 0
      minutes: 1
      seconds: 0
      milliseconds: 0
  condition: []
  action:
  - service: notify.mobile_app_oneplus_a5010
    data:
      title: Thermostat Unavailable
      message: Check to see if furnace is on!
  - service: notify.mobile_app_sm_a515w
    data:
      title: Thermostat Unavailable
      message: Check to see if furnace is on!
  mode: single
- id: '1615075704978'
  alias: Morning Sunrise
  description: ''
  trigger:
  - platform: time
    at: 06:45:00
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - service: script.turn_on
    target:
      entity_id: script.sunrise
    data:
      variables:
        light: light.wled_bed
  mode: single
- id: '1616884736419'
  alias: Close the garage when no one is home
  description: ''
  trigger:
  - platform: state
    entity_id: person.allynn
    to: not_home
  - platform: state
    entity_id: person.kyle
    to: not_home
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: person.allynn
      state: not_home
    - condition: state
      entity_id: person.kyle
      state: not_home
    - condition: state
      entity_id: person.guest
      state: not_home
    - condition: state
      entity_id: cover.garage_door
      state: open
  action:
  - service: cover.close_cover
    target:
      entity_id: cover.garage_door
  mode: single
- id: '1634020365562'
  alias: Let there be light
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.in_wall_smart_motion_dimmer_home_security_motion_detection
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: light.turn_on
    target:
      entity_id:
      - light.livingroom_pots
      - light.dining_table
      - light.kitchen
      - light.living_room_main
      - light.sink_lights
    data:
      brightness_pct: 100
  mode: single
- id: '1637868774108'
  alias: Clock Chimes - Minutes
  description: ''
  trigger:
  - platform: time_pattern
    minutes: /15
  condition:
  - condition: template
    value_template: '{{ now().minute > 10 and now().minute < 50 }}'
  - condition: not
    conditions:
    - condition: state
      entity_id: media_player.living_room
      state: playing
  action:
  - data:
      entity_id: media_player.living_room
    service: sonos.unjoin
  - data:
      volume_level: 0.25
    service: media_player.volume_set
    target:
      entity_id: media_player.living_room
  - service: media_player.play_media
    data:
      media_content_id: x-file-cifs://10.0.0.10/docs/kyle/Documents/Projects/Clock
        Chimes/{{ now().minute }}.mp3
      media_content_type: music
    target:
      entity_id: media_player.living_room
  mode: single
- id: '1637870310658'
  alias: Clock Chimes - Hour
  description: ''
  trigger:
  - platform: time_pattern
    hours: '*'
    seconds: '39'
    minutes: '59'
  condition:
  - condition: time
    after: 06:50:00
    before: '21:05:00'
  - condition: not
    conditions:
    - condition: state
      entity_id: media_player.living_room
      state: playing
  action:
  - data:
      entity_id: media_player.living_room
    service: sonos.unjoin
  - data:
      volume_level: 0.25
    service: media_player.volume_set
    target:
      entity_id: media_player.living_room
  - service: media_player.clear_playlist
    target:
      entity_id: media_player.living_room
  - service: media_player.play_media
    data:
      media_content_id: x-file-cifs://10.0.0.10/docs/kyle/Documents/Projects/Clock
        Chimes/60.mp3
      media_content_type: music
      enqueue: true
    target:
      entity_id: media_player.living_room
  - service: media_player.play_media
    data:
      media_content_id: x-file-cifs://10.0.0.10/docs/kyle/Documents/Projects/Clock
        Chimes/{% if now().hour > 12 %}{{ now().hour - 11 }}{%- else -%}{{ now().hour
        + 1 }}{%- endif %}.mp3
      media_content_type: music
      enqueue: true
    target:
      entity_id: media_player.living_room
  - service: sonos.play_queue
    target:
      entity_id: media_player.living_room
  mode: single
- id: '1639164820573'
  alias: Lights off when no one is home
  description: ''
  trigger:
  - platform: state
    entity_id: person.allynn
    to: not_home
  - platform: state
    entity_id: person.kyle
    to: not_home
  condition:
  - condition: state
    entity_id: person.allynn
    state: not_home
  - condition: state
    entity_id: person.kyle
    state: not_home
  - condition: not
    conditions:
    - condition: state
      entity_id: person.guest
      state: home
  action:
  - service: light.turn_off
    target:
      entity_id: all
  mode: single
- id: '1641689543179'
  alias: Pot lights on motion
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.living_room_dimmer_motion
    from: 'off'
    to: 'on'
  - platform: state
    entity_id: input_boolean.potsoverride
  condition:
  - condition: state
    entity_id: input_boolean.potsoverride
    state: 'off'
  action:
  - service: light.turn_on
    target:
      entity_id: light.livingroom_pots
    data:
      brightness_pct: "{% if is_state(\"light.livingroom_pots\", \"on\") -%}\n  {{\
        \ (state_attr(\"light.livingroom_pots\", \"brightness\") / 2.55 ) | round\
        \ }}\n{%- else -%}\n  {% if now().hour >=22 or now().hour < 7 %} 1\n  {% elif\
        \ now().hour >= 20 and now().hour < 22 %} 30\n  {% else %} 100\n  {% endif\
        \ %}\n{%- endif %}"
  - wait_template: '{{ is_state("binary_sensor.living_room_dimmer_motion", "off")
      }}'
  - delay:
      minutes: '{% if now().hour >=17 and now().hour < 22 %} 30 {% else %} 15 {% endif
        %}'
  - condition: state
    entity_id: input_boolean.potsoverride
    state: 'off'
  - service: light.turn_off
    target:
      entity_id: light.livingroom_pots
  mode: restart
