# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
#  latitude: !secret lat
#  longitude: !secret lon
#  elevation: 100
#  unit_system: metric
#  time_zone: America/Toronto
#  name: Home
  customize: !include customize.yaml
# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech
tts:
  - platform: google_translate

weather:
  - platform: environment_canada

cover:
  - platform: myq
    username: !secret myqu
    password: !secret myqp

#Custom component
sonos_player_modes:

recorder:
  purge_keep_days: 3
  exclude:
    domains:
      - scene
      - automation
      - sensor
    entity_globs:
      - media_player.plex_*
    entities:
      - binary_sensor.updater
      - binary_sensor.home_myq_gateway
      - input_number.baby_main_ir
      - input_boolean.reading_on
      - light.bedroom
      - light.computer_room
  include:
    entities:
      - sensor.temperature
      - sensor.weather_temperature
      - sensor.high_temperature
      - sensor.low_temperature

input_number:
  baby_main_ir:
    name: Baby Main Infrared
    initial: 255
    min: 0
    max: 255
    step: 1
    icon: mdi:lightbulb-outline

light:
  - platform: template
    lights:
      baby_main_ir:
        friendly_name: 'Baby Main Infrared'
        icon_template: mdi:lightbulb-outline
        value_template:  >-
          {% if states('input_number.baby_main_ir') | int > 0 %}
            on
          {% else %}
            off
          {% endif %}
        level_template: "{{ states('input_number.baby_main_ir') | int }}"
        turn_on:
          service: input_number.set_value
          data_template:
            entity_id: input_number.baby_main_ir
            value: 255
        turn_off:
          service: input_number.set_value
          data_template:
            entity_id: input_number.baby_main_ir
            value: 0
        set_level:
          service: input_number.set_value
          data_template:
            entity_id: input_number.baby_main_ir
            value: "{{ brightness | int }}"
  - platform: group
    name: Bedroom Lights
    entities:
      - light.bed_main
      - light.wled_bed

device_tracker:
  - platform: linksys_smart
    host: 192.168.0.2
    new_device_defaults:
      track_new_devices: false
  - platform: linksys_smart
    host: 192.168.0.3
    new_device_defaults:
      track_new_devices: false

automation: !include automations.yaml
group: !include groups.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include sensors.yaml
