# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
#  latitude: !secret lat
#  longitude: !secret lon
#  elevation: 100
#  unit_system: metric
#  time_zone: America/Toronto
#  name: Home
  customize: !include customize.yaml
# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech
tts:
  - platform: google_translate

logger:
  default: error
  logs:
    homeassistant.core: fatal

binary_sensor:
  - platform: workday
    country: CA
    province: 'ON'
    #add_holidays: #Hydro Ottawa off-peak holidays 2021
    # - "New Year’s Day"
    # - "Family Day"
    # - "Good Friday"
    # - "Victoria Day"
    # - "Canada Day"
    # - "Civic Holiday"
    # - "Labour Day"
    # - "Thanksgiving"
    # - "Christmas Day"
    # - "Boxing Day"
    #remove_holidays:

light:
  - platform: template
    lights:
      alistair_main_ir:
        friendly_name: 'Alistair Main Infrared'
        unique_id: AlistairMainInfrared
        icon_template: mdi:lightbulb-outline
        value_template:  >-
          {% if states('input_number.alistair_main_ir') | int > 0 %}
            on
          {% else %}
            off
          {% endif %}
        level_template: "{{ states('input_number.alistair_main_ir') | int }}"
        turn_on:
          service: input_number.set_value
          data_template:
            entity_id: input_number.alistair_main_ir
            value: 255
        turn_off:
          service: input_number.set_value
          data_template:
            entity_id: input_number.alistair_main_ir
            value: 0
        set_level:
          service: input_number.set_value
          data_template:
            entity_id: input_number.alistair_main_ir
            value: "{{ brightness | int }}"
      rowan_main_ir:
        friendly_name: 'Rowan Main Infrared'
        unique_id: RowanMainInfrared
        icon_template: mdi:lightbulb-outline
        value_template:  >-
          {% if states('input_number.rowan_main_ir') | int > 0 %}
            on
          {% else %}
            off
          {% endif %}
        level_template: "{{ states('input_number.rowan_main_ir') | int }}"
        turn_on:
          service: input_number.set_value
          data_template:
            entity_id: input_number.rowan_main_ir
            value: 255
        turn_off:
          service: input_number.set_value
          data_template:
            entity_id: input_number.rowan_main_ir
            value: 0
        set_level:
          service: input_number.set_value
          data_template:
            entity_id: input_number.rowan_main_ir
            value: "{{ brightness | int }}"

template:
  - sensor:
      - name: Weighted Temp
        unique_id: WeightedTemp
        unit_of_measurement: "°C"
        state: >
          {% set thermo = states("sensor.thermostat_temperature") | float(0) %}
          {% set alistair = states("sensor.alistair_room_air_temperature") | float(0) %}
          {% set rowan = states("sensor.rowan_temperature") | float(0) %}
          {% set weight = {"thermo": 1.00, "rowan": 0.00, "alistair": 0.00} %}
          {% set alistair_sleeping = is_state('light.alistair_main_ir', 'on') %}

          {% if alistair_sleeping  %}
            {% set perc_diff = 0.3 %} 
            {% set weight = {
              "thermo": weight.thermo - weight.thermo * perc_diff,
              "rowan": weight.rowan - weight.rowan * perc_diff,
              "alistair": weight.alistair + (1-weight.alistair) * perc_diff
            } %}
          {% endif %}
         
          {% set sensors = [
            [thermo, weight.thermo],
            [alistair, weight.alistair],
            [rowan, weight.rowan]
          ] %}

          {#This calculates the weighted average only if the value of the sensor is above 0#}
          {% set wAvg = namespace(x=0,y=0) %}     
          {% for sensor in sensors if sensor[0] > 0 %}
            {#Sets the output value to the only active sensor#}
            {% if loop.length == 1 %}
              {% set wAvg.x = sensor[0] %}
            {% else %}
              {% set wAvg.x = sensor[0] * sensor[1] + wAvg.x %}
              {% set wAvg.y = sensor[1] + wAvg.y %}
              {% if loop.last %}
                {% set wAvg.x = wAvg.x / wAvg.y %}
              {% endif %}
            {% endif %}
          {% endfor %}

          {{ wAvg.x | round(1) }}
  - sensor:
      - name: Hydro Ottawa Cost
        unique_id: HydroOttawaCost
        unit_of_measurement: "CAD/kWh"
        state: >
          {% set prices = {
            "tier1": 0.098,
            "tier2": 0.115,
            "off_peak": 0.082,
            "mid_peak": 0.113,
            "on_peak": 0.17,
          } %}

          {% if "on" == "on" %}
            {{ prices.tier1 }}
          {% else %}
            {% if states.binary_sensor.workday_sensor.state == "off" %}
              {{ prices.off_peak }}
            {% else %}
                {% if now().month in range(5,11) %}
                {% if now().hour in range(11,17) %} {{ prices.on_peak }}
                {% elif now().hour in [ 7,8,9,10,17,18 ] %} {{ prices.mid_peak }}
                {% else %} {{ prices.off_peak }}
                {% endif %}
              {% else %}
                {% if now().hour in range(11,17) %} {{ prices.mid_peak }}
                {% elif now().hour in [ 7,8,9,10,17,18 ] %} {{ prices.on_peak }}
                {% else %} {{ prices.off_peak }}
                {% endif %}
              {% endif %}
            {% endif %}
          {% endif %}

automation: !include automations.yaml
group: !include groups.yaml
recorder: !include recorder.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include sensors.yaml
