homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret lat
  longitude: !secret lon
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 100
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Toronto
  customize: !include customize.yaml

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
  # api_password: PASSWORD
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:
  exclude:
    domains:
      - scene
    entities:
      - zwave.kyle_multisensor
# View all events in a logbook
logbook:

# Track the sun
sun:

# Text to speech
tts:
  platform: google
zwave:
  usb_path: /dev/ttyACM0

media_player:
  - platform: plex

cover:
  - platform: myq
    username: !secret garage_user
    password: !secret garage_pass
    type: chamberlain

group: !include groups.yaml

scene: !include scenes.yaml

zone: !include zones.yaml

switch: !include switches.yaml

device_tracker: !include device_tracker.yaml

sensor: !include sensors.yaml

automation: !include automations.yaml
