- platform: time_date
  display_options:
    - 'time'
    - 'date'
    - 'date_time'
- platform: integration
  source: sensor.sonoff_s31_power
  name: Sonoff S31 Energy
  unit_prefix: k
  round: 2
- platform: integration
  source: sensor.kyle_office_outlet_power
  name: Kyle Office Outlet Energy
  unit_prefix: k
  round: 2
- platform: history_stats
  name: A/C ON today
  entity_id: binary_sensor.thermostat_cooler
  state: "on"
  type: time
  start: "{{ now().replace(hour=0, minute=0, second=0) }}"
  end: "{{ now() }}"
- platform: history_stats
  name: Furnace ON today
  entity_id: binary_sensor.thermostat_heater
  state: "on"
  type: time
  start: "{{ now().replace(hour=0, minute=0, second=0) }}"
  end: "{{ now() }}"
- platform: powercalc
  entity_id: device_tracker.cloudnas
  fixed:
    power: 67
- platform: powercalc
  entity_id: light.wled_bed
  wled:
    voltage: 5
- platform: powercalc
  entity_id: sensor.cyberpower_load
  fixed:
    power: "{{states('sensor.cyberpower_load') | int / 100 * 815}}"
