- platform: environment_canada
  station: ON/s0000430
- platform: template
  sensors:
    equipment_running:
      unique_id: ecobeeequipmentrunning
      value_template: '{{ states.climate.my_ecobee.attributes.equipment_running }}'
    aux_heat:
      unique_id: ecobeeauxheat
      value_template: '{{ states.climate.my_ecobee.attributes.aux_heat }}'
    fan:
      unique_id: ecobeefan
      value_template: '{{ states.climate.my_ecobee.attributes.fan }}'
    sun_elevation:
      unique_id: sunelevation
      unit_of_measurement: "degrees"
      value_template: '{{ states.sun.sun.attributes.elevation }}'
- platform: time_date
  display_options:
    - 'time'
    - 'date'
    - 'date_time'
