- platform: template
  sensors:
    weather_temperature:
      friendly_name: "Weather Temperature"
      unit_of_measurement: '°C'
      value_template: "{{ state_attr('weather.home', 'temperature') }}"
- platform: environment_canada
