- platform: time_date
  display_options:
    - 'time'
    - 'date'
    - 'date_time'
- platform: history_stats
  name: A/C ON today
  entity_id: binary_sensor.thermostat_cooler
  state: "on"
  type: time
  start: "{{ now().replace(hour=0, minute=0, second=0) }}"
  end: "{{ now() }}"
- platform: history_stats
  name: Furnace ON today
  entity_id: binary_sensor.thermostat_heater
  state: "on"
  type: time
  start: "{{ now().replace(hour=0, minute=0, second=0) }}"
  end: "{{ now() }}"
- platform: history_stats
  name: Hot Water Heater ON today
  entity_id: binary_sensor.hot_water_heater_state 
  state: "on"
  type: time
  start: "{{ now().replace(hour=0, minute=0, second=0) }}"
  end: "{{ now() }}"
    #- platform: powercalc
    #  entity_id: sensor.cyberpower_load
    #  fixed:
    #    power: "{{states('sensor.cyberpower_load') | int / 100 * 815}}"
