- platform: environment_canada
- platform: template
  sensors:
    equipment_running:
      unique_id: ecobeeequipmentrunning
      value_template: '{{ states.climate.my_ecobee.attributes.equipment_running }}'
    aux_heat:
      unique_id: ecobeeauxheat
      value_template: '{{ states.climate.my_ecobee.attributes.aux_heat }}'
    fan:
      unique_id: ecobeefan
      value_template: '{{ states.climate.my_ecobee.attributes.fan }}'
